Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    
    
    config.vm.define "cicd-jenkins" do |c|
      c.vm.hostname = "jenkins"
      
      #c.vm.network "private_network", ip: "192.168.56.1" #bridge: 'wlp3s0' 
      
      c.vm.provision "shell", path: "vm_config.sh"
  
      c.vm.provider "virtualbox" do |p|
          p.name = "cicd-jenkins"
          p.gui = false
          p.memory = 2048
          p.cpus = 2
      end 
  
    end
    
  end